export const level3 = {
    name: 'Neon Factory',
    music: 'level2',
    spawn: { x: 80, y: 252 },
    background: 'assets/backgrounds/level3-bg.png',

    platforms: [
        { x: 0, y: 412, width: 500, height: 40 },

        { x: 620, y: 362, width: 210, height: 32 },
        { x: 920, y: 312, width: 190, height: 32 },
        { x: 1210, y: 372, width: 260, height: 32 },

        { x: 1580, y: 292, width: 220, height: 32 },
        { x: 1900, y: 352, width: 260, height: 32 },
        { x: 2260, y: 272, width: 230, height: 32 },

        { x: 2620, y: 382, width: 360, height: 40 },
        { x: 3120, y: 332, width: 280, height: 32 },
        { x: 3540, y: 402, width: 620, height: 40 },
    ],

    gems: [
        { x: 180, y: 342, collected: false },
        { x: 300, y: 342, collected: false },

        { x: 680, y: 292, collected: false },
        { x: 760, y: 292, collected: false },

        { x: 965, y: 242, collected: false },
        { x: 1045, y: 242, collected: false },

        { x: 1280, y: 302, collected: false },
        { x: 1380, y: 302, collected: false },

        { x: 1640, y: 222, collected: false },
        { x: 1720, y: 222, collected: false },

        { x: 1970, y: 282, collected: false },
        { x: 2360, y: 202, collected: false },

        { x: 2720, y: 312, collected: false },
        { x: 2860, y: 312, collected: false },

        { x: 3220, y: 262, collected: false },

        { x: 3660, y: 332, collected: false },
        { x: 3820, y: 332, collected: false },
        { x: 3980, y: 332, collected: false },
    ],

    bonusBlocks: [
        {
            x: 760,
            y: 282,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'energy',
        },
        {
            x: 1320,
            y: 242,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'random',
        },
        {
            x: 2320,
            y: 192,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
        },
        {
            x: 3200,
            y: 242,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'life',
        },
    ],

    checkpoints: [
        { x: 1580, y: 250, width: 60, height: 80, activated: false },
        { x: 2620, y: 340, width: 60, height: 80, activated: false },
    ],

    hackTerminals: [
        {
            x: 1580,
            y: 200,
            width: 36,
            height: 52,
            difficulty: 'hard',
            reward: 'secret_area',
            targetId: 'secret',
            secretPlatforms: [
                { x: 1700, y: 160, width: 200, height: 28 },
            ],
            secretWeapon: 'plasma',
            secretX: 1750,
            secretY: 160,
            hacked: false,
            nearPlayer: false,
        },
    ],

    enemies: [
        {
            x: 690,
            y: 312,
            width: 46,
            height: 50,
            minX: 630,
            maxX: 820,
            speed: 130,
            direction: 1,
            health: 1,
            active: true,
        },
        // Drohne in der Factory
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 400,
            shootRangeY: 200,
            projectileSpeed: 300,
            projectileColor: '#ff6b00',
            x: 1100,
            y: 180,
            width: 38,
            height: 38,
            minX: 920,
            maxX: 1470,
            speed: 75,
            direction: -1,
            health: 2,
            active: true,
        },
        {
            x: 1260,
            y: 322,
            width: 46,
            height: 50,
            minX: 1220,
            maxX: 1460,
            speed: 145,
            direction: -1,
            health: 1,
            active: true,
        },
        // Schild-Gegner
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 480,
            shootRangeY: 180,
            projectileSpeed: 320,
            projectileColor: '#3b82f6',
            x: 1640,
            y: 242,
            width: 46,
            height: 50,
            minX: 1580,
            maxX: 1800,
            speed: 70,
            direction: 1,
            health: 3,
            shieldHP: 4,
            active: true,
        },
        {
            x: 1950,
            y: 302,
            width: 46,
            height: 50,
            minX: 1910,
            maxX: 2150,
            speed: 160,
            direction: 1,
            health: 2,
            active: true,
        },
        // Mech in der Factory!
        {
            type: 'mech',
            x: 2700,
            y: 318,
            width: 56,
            height: 64,
            minX: 2620,
            maxX: 2960,
            speed: 55,
            direction: -1,
            health: 7,
            chargeSpeed: 700,
            chargeRange: 400,
            active: true,
        },
        // Turret auf der hohen Plattform
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.8,
            shootRangeX: 550,
            shootRangeY: 400,
            projectileSpeed: 400,
            projectileColor: '#a855f7',
            x: 2340,
            y: 222,
            width: 42,
            height: 42,
            minX: 2340,
            maxX: 2382,
            speed: 0,
            direction: 1,
            health: 5,
            active: true,
        },
        {
            x: 3660,
            y: 352,
            width: 46,
            height: 50,
            minX: 3560,
            maxX: 4140,
            speed: 185,
            direction: 1,
            health: 3,
            active: true,
        },
        // Zweiter Schild-Gegner am Ende
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 340,
            projectileColor: '#3b82f6',
            x: 3800,
            y: 352,
            width: 46,
            height: 50,
            minX: 3560,
            maxX: 4060,
            speed: 75,
            direction: -1,
            health: 4,
            shieldHP: 3,
            active: true,
        },
    ],

    fx: {
        stars: false,
        fog: true,
        rain: true,
        scanlines: true,
        neonDust: true,
    },

    exit: {
        x: 4060,
        y: 302,
        width: 70,
        height: 100,
        locked: false,
    },
};