export const level8 = {
    name: 'Cipher Deep',
    music: 'level4',
    spawn: { x: 80, y: 252 },
    background: 'assets/backgrounds/level3-bg.png',

    platforms: [
        // Starting area
        { x: 0, y: 412, width: 480, height: 40 },

        // Triple ascent - rising platforms
        { x: 580, y: 362, width: 180, height: 32 },
        { x: 840, y: 302, width: 160, height: 32 },
        { x: 1080, y: 242, width: 180, height: 32 },

        // Hovering drone zone
        { x: 1340, y: 332, width: 220, height: 32 },
        { x: 1640, y: 282, width: 180, height: 32 },
        { x: 1900, y: 342, width: 200, height: 32 },

        // Mech gauntlet - long flat arena
        { x: 2200, y: 402, width: 600, height: 40 },
        { x: 2400, y: 312, width: 180, height: 32 },

        // Vertical tower section
        { x: 2920, y: 402, width: 220, height: 40 },
        { x: 2960, y: 312, width: 180, height: 32 },
        { x: 2940, y: 222, width: 160, height: 32 },
        { x: 2920, y: 152, width: 180, height: 28 },

        // Bridge of death - narrow with turrets
        { x: 3200, y: 302, width: 140, height: 32 },
        { x: 3440, y: 302, width: 140, height: 32 },
        { x: 3680, y: 302, width: 140, height: 32 },

        // Pre-boss arena
        { x: 3920, y: 402, width: 500, height: 40 },
        { x: 4020, y: 312, width: 180, height: 32 },
        { x: 4220, y: 252, width: 160, height: 32 },

        // Exit platform
        { x: 4520, y: 402, width: 300, height: 40 },
    ],

    shadowPlatforms: [
        {
            x: 1180,
            y: 140,
            width: 140,
            height: 24,
        },
        {
            x: 2980,
            y: 80,
            width: 120,
            height: 24,
        },
        {
            x: 4100,
            y: 170,
            width: 140,
            height: 24,
        },
    ],

    gems: [
        { x: 170, y: 342, collected: false },
        { x: 310, y: 342, collected: false },

        { x: 640, y: 292, collected: false },
        { x: 900, y: 232, collected: false },
        { x: 1140, y: 172, collected: false },

        { x: 1410, y: 262, collected: false },
        { x: 1710, y: 212, collected: false },
        { x: 1970, y: 272, collected: false },

        { x: 2360, y: 332, collected: false },
        { x: 2500, y: 332, collected: false },
        { x: 2660, y: 332, collected: false },

        { x: 3000, y: 252, collected: false },
        { x: 2980, y: 152, collected: false },

        { x: 3260, y: 242, collected: false },
        { x: 3500, y: 242, collected: false },
        { x: 3740, y: 242, collected: false },

        { x: 4080, y: 242, collected: false },
        { x: 4620, y: 332, collected: false },
    ],

    bonusBlocks: [
        {
            x: 430,
            y: 292,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'energy',
        },
        {
            x: 1120,
            y: 132,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'laser',
        },
        {
            x: 2450,
            y: 232,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'life',
        },
        {
            x: 2980,
            y: 72,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'plasma',
        },
    ],

    keys: [
        { x: 1140, y: 170 },
        { x: 2980, y: 90 },
        { x: 4080, y: 190 },
    ],

    checkpoints: [
        { x: 2200, y: 320, width: 60, height: 80, activated: false },
        { x: 3920, y: 320, width: 60, height: 80, activated: false },
    ],

    enemies: [
        // Ascent: shield + walker
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 480,
            shootRangeY: 180,
            projectileSpeed: 320,
            projectileColor: '#3b82f6',
            x: 640,
            y: 312,
            width: 46,
            height: 50,
            minX: 580,
            maxX: 740,
            speed: 80,
            direction: 1,
            health: 3,
            shieldHP: 4,
            active: true,
        },
        {
            x: 1130,
            y: 192,
            width: 46,
            height: 50,
            minX: 1080,
            maxX: 1240,
            speed: 150,
            direction: -1,
            health: 3,
            active: true,
            canShoot: true,
            shootDelay: 1.3,
            shootRangeX: 480,
            shootRangeY: 200,
            projectileSpeed: 360,
            projectileColor: '#ff003c',
        },

        // Drone zone: two drones
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 420,
            shootRangeY: 250,
            projectileSpeed: 300,
            projectileColor: '#ff6b00',
            x: 1440,
            y: 170,
            width: 38,
            height: 38,
            minX: 1340,
            maxX: 1560,
            speed: 80,
            direction: -1,
            health: 3,
            active: true,
        },
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 400,
            shootRangeY: 250,
            projectileSpeed: 320,
            projectileColor: '#ff6b00',
            x: 1740,
            y: 140,
            width: 38,
            height: 38,
            minX: 1640,
            maxX: 1820,
            speed: 70,
            direction: 1,
            health: 3,
            active: true,
        },
        {
            // Walker below drones
            x: 1960,
            y: 292,
            width: 46,
            height: 50,
            minX: 1900,
            maxX: 2080,
            speed: 165,
            direction: -1,
            health: 3,
            active: true,
        },

        // Mech gauntlet: two mechs + support
        {
            type: 'mech',
            x: 2340,
            y: 338,
            width: 56,
            height: 64,
            minX: 2200,
            maxX: 2600,
            speed: 55,
            direction: 1,
            health: 8,
            chargeSpeed: 720,
            chargeRange: 400,
            active: true,
        },
        {
            type: 'mech',
            x: 2640,
            y: 338,
            width: 56,
            height: 64,
            minX: 2500,
            maxX: 2780,
            speed: 60,
            direction: -1,
            health: 8,
            chargeSpeed: 750,
            chargeRange: 420,
            active: true,
        },
        {
            // Elevated walker for crossfire
            x: 2440,
            y: 262,
            width: 46,
            height: 50,
            minX: 2400,
            maxX: 2560,
            speed: 130,
            direction: 1,
            health: 3,
            active: true,
            canShoot: true,
            shootDelay: 1.2,
            shootRangeX: 520,
            shootRangeY: 200,
            projectileSpeed: 380,
            projectileColor: '#ff003c',
        },

        // Bridge of death: turrets on every other platform
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.8,
            shootRangeX: 500,
            shootRangeY: 400,
            projectileSpeed: 400,
            projectileColor: '#a855f7',
            x: 3240,
            y: 252,
            width: 42,
            height: 42,
            minX: 3240,
            maxX: 3282,
            speed: 0,
            direction: -1,
            health: 5,
            active: true,
        },
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.75,
            shootRangeX: 520,
            shootRangeY: 400,
            projectileSpeed: 420,
            projectileColor: '#a855f7',
            x: 3720,
            y: 252,
            width: 42,
            height: 42,
            minX: 3720,
            maxX: 3762,
            speed: 0,
            direction: 1,
            health: 5,
            active: true,
        },

        // Pre-boss: shield + turret combo
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.4,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 360,
            projectileColor: '#3b82f6',
            x: 4060,
            y: 352,
            width: 46,
            height: 50,
            minX: 3920,
            maxX: 4200,
            speed: 90,
            direction: -1,
            health: 4,
            shieldHP: 5,
            active: true,
        },
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.7,
            shootRangeX: 560,
            shootRangeY: 400,
            projectileSpeed: 440,
            projectileColor: '#a855f7',
            x: 4070,
            y: 202,
            width: 42,
            height: 42,
            minX: 4070,
            maxX: 4112,
            speed: 0,
            direction: 1,
            health: 6,
            active: true,
        },
        {
            // Drone over pre-boss area
            type: 'drone',
            canShoot: true,
            shootDelay: 1.5,
            shootRangeX: 450,
            shootRangeY: 250,
            projectileSpeed: 340,
            projectileColor: '#ff6b00',
            x: 4160,
            y: 140,
            width: 38,
            height: 38,
            minX: 3920,
            maxX: 4380,
            speed: 85,
            direction: -1,
            health: 3,
            active: true,
        },
    ],

    fx: {
        stars: false,
        fog: true,
        rain: true,
        scanlines: true,
        neonDust: true,
        sparks: true,
        warningLights: true,
    },

    exit: {
        x: 4720,
        y: 302,
        width: 70,
        height: 100,
        locked: true,
        keysRequired: 3,
        unlockMode: 'allGemsOrEnemiesOrKeys',
    },
};
