export const level6 = {
    name: 'Data Storm',
    music: 'level2',
    spawn: { x: 80, y: 252 },
    background: 'assets/backgrounds/level2-bg.png',

    platforms: [
        // Starting area - wide safe ground
        { x: 0, y: 412, width: 460, height: 40 },

        // First ascent - stepping stones
        { x: 540, y: 372, width: 200, height: 32 },
        { x: 820, y: 322, width: 220, height: 32 },
        { x: 1100, y: 282, width: 180, height: 32 },

        // Drone corridor - narrow platforms with gaps
        { x: 1360, y: 332, width: 160, height: 32 },
        { x: 1600, y: 282, width: 140, height: 32 },
        { x: 1820, y: 332, width: 160, height: 32 },

        // Mid-level arena - wide combat zone
        { x: 2060, y: 402, width: 500, height: 40 },
        { x: 2300, y: 322, width: 200, height: 32 },

        // Turret alley - elevated platforms with turrets below
        { x: 2660, y: 272, width: 220, height: 32 },
        { x: 2960, y: 302, width: 180, height: 32 },
        { x: 3220, y: 362, width: 200, height: 32 },

        // Final approach - vertical challenge
        { x: 3520, y: 402, width: 300, height: 40 },
        { x: 3560, y: 302, width: 180, height: 32 },
        { x: 3800, y: 242, width: 200, height: 32 },

        // Exit platform
        { x: 4080, y: 402, width: 360, height: 40 },
    ],

    shadowPlatforms: [
        {
            x: 1200,
            y: 180,
            width: 140,
            height: 24,
        },
        {
            x: 2760,
            y: 190,
            width: 140,
            height: 24,
        },
    ],

    gems: [
        { x: 170, y: 342, collected: false },
        { x: 290, y: 342, collected: false },

        { x: 600, y: 302, collected: false },
        { x: 890, y: 252, collected: false },

        { x: 1150, y: 212, collected: false },
        { x: 1420, y: 282, collected: false },
        { x: 1660, y: 222, collected: false },

        { x: 2120, y: 332, collected: false },
        { x: 2260, y: 332, collected: false },
        { x: 2380, y: 252, collected: false },

        { x: 2720, y: 212, collected: false },
        { x: 3020, y: 242, collected: false },

        { x: 3600, y: 242, collected: false },
        { x: 3860, y: 182, collected: false },

        { x: 4160, y: 332, collected: false },
        { x: 4280, y: 332, collected: false },
    ],

    bonusBlocks: [
        {
            x: 420,
            y: 292,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'energy',
        },
        {
            x: 1140,
            y: 162,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'spread',
        },
        {
            x: 2340,
            y: 242,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'life',
        },
        {
            x: 3000,
            y: 212,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'laser',
        },
        {
            x: 3840,
            y: 152,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'random',
            randomPool: ['gem', 'energy', 'life', 'weapon'],
            weaponId: 'plasma',
        },
    ],

    keys: [
        { x: 880, y: 240 },
        { x: 2710, y: 200 },
        { x: 3850, y: 170 },
    ],

    checkpoints: [
        { x: 2060, y: 320, width: 60, height: 80, activated: false },
        { x: 3520, y: 320, width: 60, height: 80, activated: false },
    ],

    enemies: [
        // Early walkers
        {
            x: 600,
            y: 322,
            width: 46,
            height: 50,
            minX: 540,
            maxX: 720,
            speed: 120,
            direction: 1,
            health: 2,
            active: true,
        },

        // Drone pair in the drone corridor
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 2.0,
            shootRangeX: 400,
            shootRangeY: 220,
            projectileSpeed: 280,
            projectileColor: '#ff6b00',
            x: 1450,
            y: 160,
            width: 38,
            height: 38,
            minX: 1360,
            maxX: 1520,
            speed: 65,
            direction: -1,
            health: 2,
            active: true,
        },
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 380,
            shootRangeY: 220,
            projectileSpeed: 300,
            projectileColor: '#ff6b00',
            x: 1690,
            y: 140,
            width: 38,
            height: 38,
            minX: 1600,
            maxX: 1760,
            speed: 75,
            direction: 1,
            health: 2,
            active: true,
        },

        // Walker on narrow platform
        {
            x: 1850,
            y: 282,
            width: 46,
            height: 50,
            minX: 1820,
            maxX: 1960,
            speed: 140,
            direction: -1,
            health: 2,
            active: true,
        },

        // Arena: Shield + Mech combo
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 320,
            projectileColor: '#3b82f6',
            x: 2140,
            y: 352,
            width: 46,
            height: 50,
            minX: 2060,
            maxX: 2350,
            speed: 80,
            direction: -1,
            health: 3,
            shieldHP: 4,
            active: true,
        },
        {
            type: 'mech',
            x: 2380,
            y: 338,
            width: 56,
            height: 64,
            minX: 2260,
            maxX: 2540,
            speed: 55,
            direction: -1,
            health: 7,
            chargeSpeed: 700,
            chargeRange: 400,
            active: true,
        },

        // Turret alley
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.85,
            shootRangeX: 520,
            shootRangeY: 400,
            projectileSpeed: 400,
            projectileColor: '#a855f7',
            x: 2700,
            y: 362,
            width: 42,
            height: 42,
            minX: 2700,
            maxX: 2742,
            speed: 0,
            direction: 1,
            health: 5,
            active: true,
        },
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.9,
            shootRangeX: 480,
            shootRangeY: 400,
            projectileSpeed: 380,
            projectileColor: '#a855f7',
            x: 3050,
            y: 342,
            width: 42,
            height: 42,
            minX: 3050,
            maxX: 3092,
            speed: 0,
            direction: -1,
            health: 5,
            active: true,
        },

        // Drone hovering over turret alley
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 2.2,
            shootRangeX: 450,
            shootRangeY: 250,
            projectileSpeed: 300,
            projectileColor: '#ff6b00',
            x: 2900,
            y: 150,
            width: 38,
            height: 38,
            minX: 2660,
            maxX: 3140,
            speed: 85,
            direction: -1,
            health: 3,
            active: true,
        },

        // Final approach enemies
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 480,
            shootRangeY: 180,
            projectileSpeed: 340,
            projectileColor: '#3b82f6',
            x: 3580,
            y: 352,
            width: 46,
            height: 50,
            minX: 3520,
            maxX: 3780,
            speed: 85,
            direction: 1,
            health: 4,
            shieldHP: 4,
            active: true,
        },
        {
            x: 4200,
            y: 352,
            width: 46,
            height: 50,
            minX: 4080,
            maxX: 4380,
            speed: 175,
            direction: -1,
            health: 4,
            active: true,
            canShoot: true,
            shootDelay: 1.2,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 360,
            projectileColor: '#ff003c',
        },

        // Ninja assassin — stalks & ambushes
        {
            type: 'ninja',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 400,
            shootRangeY: 200,
            projectileSpeed: 380,
            projectileColor: '#22d3ee',
            x: 3820,
            y: 192,
            width: 42,
            height: 50,
            minX: 3800,
            maxX: 3980,
            speed: 170,
            direction: -1,
            health: 3,
            active: true,
        },
    ],

    fx: {
        stars: false,
        fog: true,
        rain: true,
        scanlines: true,
        neonDust: true,
        sparks: true,
    },

    exit: {
        x: 4340,
        y: 302,
        width: 70,
        height: 100,
        locked: true,
        keysRequired: 3,
        unlockMode: 'allGemsOrEnemiesOrKeys',
    },
};
