export const level7 = {
    name: 'Chrome Void',
    music: 'level2',
    spawn: { x: 80, y: 252 },
    background: 'assets/backgrounds/level1-bg.png',

    platforms: [
        // Starting zone
        { x: 0, y: 412, width: 500, height: 40 },

        // Shield gauntlet - multiple levels
        { x: 600, y: 372, width: 240, height: 32 },
        { x: 920, y: 322, width: 200, height: 32 },
        { x: 1200, y: 372, width: 240, height: 32 },

        // Elevated turret platform
        { x: 1520, y: 272, width: 200, height: 32 },

        // Mid-level safe zone
        { x: 1820, y: 402, width: 400, height: 40 },

        // Turret alley - long narrow stretch
        { x: 2340, y: 362, width: 180, height: 32 },
        { x: 2620, y: 332, width: 160, height: 32 },
        { x: 2880, y: 362, width: 180, height: 32 },

        // Elevated sniper perch
        { x: 3140, y: 252, width: 160, height: 32 },

        // Combat arena
        { x: 3400, y: 402, width: 600, height: 40 },
        { x: 3540, y: 312, width: 200, height: 32 },
        { x: 3800, y: 252, width: 180, height: 32 },

        // Final corridor
        { x: 4120, y: 382, width: 260, height: 32 },
        { x: 4500, y: 402, width: 380, height: 40 },
    ],

    shadowPlatforms: [
        {
            x: 1060,
            y: 200,
            width: 140,
            height: 24,
        },
        {
            x: 3200,
            y: 170,
            width: 140,
            height: 24,
        },
        {
            x: 3660,
            y: 170,
            width: 160,
            height: 24,
        },
    ],

    gems: [
        { x: 170, y: 342, collected: false },
        { x: 300, y: 342, collected: false },
        { x: 420, y: 342, collected: false },

        { x: 670, y: 302, collected: false },
        { x: 990, y: 252, collected: false },
        { x: 1280, y: 302, collected: false },

        { x: 1580, y: 202, collected: false },

        { x: 1900, y: 332, collected: false },
        { x: 2040, y: 332, collected: false },

        { x: 2400, y: 302, collected: false },
        { x: 2680, y: 262, collected: false },
        { x: 2940, y: 302, collected: false },

        { x: 3190, y: 192, collected: false },

        { x: 3510, y: 242, collected: false },
        { x: 3760, y: 182, collected: false },
        { x: 3960, y: 332, collected: false },

        { x: 4200, y: 302, collected: false },
        { x: 4600, y: 332, collected: false },
    ],

    bonusBlocks: [
        {
            x: 470,
            y: 292,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'bounce',
        },
        {
            x: 960,
            y: 232,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'energy',
        },
        {
            x: 1920,
            y: 312,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'life',
        },
        {
            x: 3180,
            y: 172,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'weapon',
            weaponId: 'plasma',
        },
        {
            x: 3820,
            y: 172,
            width: 42,
            height: 42,
            used: false,
            bumpTimer: 0,
            reward: 'random',
            randomPool: ['gem', 'energy', 'life', 'weapon'],
            weaponId: 'wave',
        },
    ],

    keys: [
        { x: 980, y: 240 },
        { x: 3190, y: 180 },
        { x: 3760, y: 170 },
    ],

    checkpoints: [
        { x: 1820, y: 320, width: 60, height: 80, activated: false },
        { x: 3400, y: 320, width: 60, height: 80, activated: false },
    ],

    enemies: [
        // Shield wall - two shield enemies blocking the path
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 450,
            shootRangeY: 180,
            projectileSpeed: 320,
            projectileColor: '#3b82f6',
            x: 680,
            y: 322,
            width: 46,
            height: 50,
            minX: 600,
            maxX: 820,
            speed: 75,
            direction: 1,
            health: 3,
            shieldHP: 4,
            active: true,
        },
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 2.0,
            shootRangeX: 450,
            shootRangeY: 180,
            projectileSpeed: 300,
            projectileColor: '#3b82f6',
            x: 1260,
            y: 322,
            width: 46,
            height: 50,
            minX: 1200,
            maxX: 1420,
            speed: 80,
            direction: -1,
            health: 3,
            shieldHP: 3,
            active: true,
        },

        // Walker between shields
        {
            x: 1000,
            y: 272,
            width: 46,
            height: 50,
            minX: 920,
            maxX: 1100,
            speed: 140,
            direction: -1,
            health: 2,
            active: true,
            canShoot: true,
            shootDelay: 1.4,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 340,
            projectileColor: '#ff003c',
        },

        // Turret on elevated platform - covers the approach
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.75,
            shootRangeX: 580,
            shootRangeY: 400,
            projectileSpeed: 420,
            projectileColor: '#a855f7',
            x: 1580,
            y: 222,
            width: 42,
            height: 42,
            minX: 1580,
            maxX: 1622,
            speed: 0,
            direction: -1,
            health: 5,
            active: true,
        },

        // Drone over the safe zone
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.8,
            shootRangeX: 420,
            shootRangeY: 250,
            projectileSpeed: 300,
            projectileColor: '#ff6b00',
            x: 1920,
            y: 160,
            width: 38,
            height: 38,
            minX: 1820,
            maxX: 2220,
            speed: 70,
            direction: 1,
            health: 2,
            active: true,
        },

        // Turret alley: two turrets flanking
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.9,
            shootRangeX: 500,
            shootRangeY: 400,
            projectileSpeed: 380,
            projectileColor: '#a855f7',
            x: 2380,
            y: 312,
            width: 42,
            height: 42,
            minX: 2380,
            maxX: 2422,
            speed: 0,
            direction: 1,
            health: 6,
            active: true,
        },
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.85,
            shootRangeX: 520,
            shootRangeY: 400,
            projectileSpeed: 400,
            projectileColor: '#a855f7',
            x: 2920,
            y: 312,
            width: 42,
            height: 42,
            minX: 2920,
            maxX: 2962,
            speed: 0,
            direction: -1,
            health: 6,
            active: true,
        },

        // Sniper turret on elevated perch
        {
            type: 'turret',
            canShoot: true,
            shootDelay: 0.7,
            shootRangeX: 600,
            shootRangeY: 400,
            projectileSpeed: 440,
            projectileColor: '#a855f7',
            x: 3180,
            y: 202,
            width: 42,
            height: 42,
            minX: 3180,
            maxX: 3222,
            speed: 0,
            direction: 1,
            health: 5,
            active: true,
        },

        // Combat arena: Shield + Mech + Walker
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 340,
            projectileColor: '#3b82f6',
            x: 3500,
            y: 352,
            width: 46,
            height: 50,
            minX: 3400,
            maxX: 3600,
            speed: 85,
            direction: 1,
            health: 4,
            shieldHP: 5,
            active: true,
        },
        {
            type: 'mech',
            x: 3760,
            y: 338,
            width: 56,
            height: 64,
            minX: 3540,
            maxX: 3940,
            speed: 60,
            direction: -1,
            health: 8,
            chargeSpeed: 750,
            chargeRange: 420,
            active: true,
        },
        {
            x: 3600,
            y: 262,
            width: 46,
            height: 50,
            minX: 3540,
            maxX: 3720,
            speed: 160,
            direction: 1,
            health: 3,
            active: true,
            canShoot: true,
            shootDelay: 1.3,
            shootRangeX: 480,
            shootRangeY: 200,
            projectileSpeed: 360,
            projectileColor: '#ff003c',
        },

        // Drone covering final corridor
        {
            type: 'drone',
            canShoot: true,
            shootDelay: 1.6,
            shootRangeX: 400,
            shootRangeY: 250,
            projectileSpeed: 320,
            projectileColor: '#ff6b00',
            x: 4240,
            y: 160,
            width: 38,
            height: 38,
            minX: 4120,
            maxX: 4380,
            speed: 80,
            direction: -1,
            health: 3,
            active: true,
        },

        // Final shield guard
        {
            type: 'shield',
            canShoot: true,
            shootDelay: 1.5,
            shootRangeX: 500,
            shootRangeY: 180,
            projectileSpeed: 360,
            projectileColor: '#3b82f6',
            x: 4600,
            y: 352,
            width: 46,
            height: 50,
            minX: 4500,
            maxX: 4820,
            speed: 90,
            direction: -1,
            health: 4,
            shieldHP: 4,
            active: true,
        },
    ],

    fx: {
        stars: true,
        fog: true,
        rain: false,
        scanlines: true,
        neonDust: true,
        sparks: true,
        warningLights: true,
    },

    exit: {
        x: 4780,
        y: 302,
        width: 70,
        height: 100,
        locked: true,
        keysRequired: 3,
        unlockMode: 'allGemsOrEnemiesOrKeys',
    },
};
